# =========================
# Run
# =========================
run:
  run_dir: /develop/code/runs/cyclenet/remote_sensing/oem_only
  ckpt_name: step-20000.ckpt

# =========================
# Dataset
# =========================
data:
  src_dir: /cgi/data/nvesd/workspaces/logan/data/remote_sensing/tiled/sim/synrs3d
  # -- [Source Domain] - (0): Sim, (1): Real
  src_idx: 0

  rgb_parent_dirs:
    - opt

  out_dir: /cgi/data/nvesd/workspaces/logan/data/remote_sensing/tiled/cyclenet_sim/synrs3d/oem_only/step-20000_strength-0.3_cfg-3.0
  image_size: 256

# =========================
# Sampling
# =========================
sampling:
  batch_size: 16
  sampler: ddim
  ddim_steps: 100
  eta: 0
  cfg_weight: 3.0
  noise_strength: 0.3