[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pixel-cyclenet"
version = "0.1.0"
description = "Pixel-level CycleNet implementation."
readme = "README.md"
license = "MIT"

dependencies = [
    "numpy",
    "matplotlib",
    "scikit-learn",
    "opencv-python",
    "tqdm",
    "omegaconf",
    "wandb",
    "moviepy",
    "imageio",
    "opencv-python",
    "albumentations",
    "torchmetrics",
    "sympy==1.13.1",
    "transformers",
    "umap-learn",
    "lpips",
]

[tool.setuptools.packages.find]
where = ["src"]
