# =========================
# Run
# =========================
run:
  seed: 42

# =========================
# Dataset
# =========================
data:
  # translated_dir: /develop/data/remote_sensing/tiled/projection/cyclenet_sim_proj/all_real/step-20000_strength-0.4_cfg-2.0
  real_dir: /develop/data/remote_sensing/tiled/projection/oem_proj
  sim_dir: /develop/data/remote_sensing/tiled/projection/sim_proj

  # out_dir: /develop/code/eval/cyclenet/remote_sensing/project_translated/all_real/step-20000_strength-0.4_cfg-2.0
  translated_dir_template: /develop/data/remote_sensing/tiled/projection/cyclenet_sim_proj/oem_only/ema/step-{step}/strength-{strength}/cfg-{cfg}
  out_dir_template: /develop/code/eval/cyclenet/remote_sensing/project_translated/oem_only/ema/step-{step}/strength-{strength}/cfg-{cfg}

  reference_cache_dir: /develop/code/eval/cyclenet/remote_sensing/project_translated/reference_cache

  image_size: 256

# =========================
# Sweep
# =========================
# If sweep is set, the script loops over every (step, strength, cfg) combination.
# data.translated_dir_template is required in sweep mode.
# If data.out_dir_template is omitted, outputs are written under data.out_dir / step-..._strength-..._cfg-...
#
sweep:
  embedding_models: [clip, inception, deeplab]
  projection_methods: [umap, pca]
  steps: [2500]
  cfg_weights: [1.0, 2.0, 3.0, 4.0, 5.0]
  noise_strengths: [0.1, 0.2, 0.3, 0.4, 0.5]

# =========================
# Embedding
# =========================
embedding:
  # -- clip, inception, or deeplab
  model: inception

  clip_path: /cgi/data/nvesd/workspaces/logan/data/pre_trained_models/clip
  deeplab_path: /cgi/data/nvesd/workspaces/logan/code/land_mapping/runs/deeplab/oem_subset/real-sim/training/checkpoints/step-50000.ckpt
  
  feature_layer: prelogits
  batch_size: 32
  num_samples: 2000

# =========================
# Projection
# =========================
projection:
  # -- pca, or umap
  method: umap
  n_components: 2
  random_state: 42

# =========================
# Plotting
# =========================
plotting:
  title: 2D Embedding Projection
  axis_pad_frac: 0.25

  points:
    show: true
    alpha: 0.3
    max_points_per_group: 500
    size: 10

  density:
    show: true
    alpha: 0.7
    fill: false

  marginal:
    show: true

  labels:
    sim: Sim
    real: Real
    translated: Translated

  colors:
    sim: "#55A868"       
    real: "#C44E52"      
    translated: "#4C72B0"
